name: Publish Docker Image to Docker Hub

on:
  push:
    branches: ['25-github-action-to-build-and-push-docker-image']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Publish to DockerHub
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: itjobmarketanalytics/rest-api:dev
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

